version: "3.7"
services:
  superset:
    build: .
    ports:
      - 8088:8088
    environment:
      - SUPERSET_SECRET_KEY=someverysecretrandomkey
      - SUPERSET_PUBLIC_ROLE_LIKE=Alpha
      - SUPERSET_SQLALCHEMY_EXAMPLES_URI=iris://_system:SYS@iris:1972/USER

  iris:
    image: intersystemsdc/iris-community
    ports:
      - 1972
      - 52773
    environment:
      - IRIS_USERNAME=_SYSTEM
      - IRIS_PASSWORD=SYS
