version: "3.7"
services:
  superset:
    build: .
    ports:
      - 8088:8088
    environment:
      - SUPERSET_SECRET_KEY=someverysecretrandomkey
      - SUPERSET_PUBLIC_ROLE_LIKE=Alpha
      - SUPERSET_SQLALCHEMY_EXAMPLES_URI=iris://_system:SYS@iris:1972/USER

  iris:
    image: containers.intersystems.com/intersystems/iris-community:2023.1.0.226.0
    ports:
      - 1972
      - 52773
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
